# ~/.zshrc
alias ls="exa --icons --color=always --group-directories-first"
alias la="exa --icons -abghHliS --color=always --group-directories-first"
alias l="exa --icons -la --color=always --group-directories-first"
alias ll="exa --icons -a --color=always --group-directories-first"
alias lt="exa --icons -T --color=always --group-directories-first"
alias l.='exa -a | egrep "^\."'
alias lv='/home/pheon/.local/bin/lvim'
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep='fgrep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
alias x="exit"
alias ytv="youtube-dl"
alias shuffle="mpv --shuffle"
alias mus="mocp"
alias msh="mocp -t shuffle"
alias mnx="mocp -t autonext"
alias mre="mocp -t repeat"
alias mob="mocp -r && mocp -i | grep File"
alias mon="mocp -f && mocp -i | grep File"
alias mop="mocp -G"
alias mov="mocp -v"
alias moi="mocp -i | grep File"
alias vol="pulsemixer"
alias pmu="cd /home/pheon/Music"
alias dw="cd /home/pheon/Downloads/"
alias play="cd /home/pheon/Documents/Play-Ground/"
alias dwm="cd /home/pheon/Downloads/Movies/"
alias dc="cd /home/pheon/Documents/"
alias xf="exiftool"
alias nvg="wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash"
alias nvl="nvm install node" #latest
alias nvi="nvm install" #nvi 10.18.1
alias apnx="pnpx create-next-app"
alias apre="pnpx create-react-app"
alias apvi="pnpm create vite || npm create vite"
alias apsv="pnpx degit sveltejs/template"
alias pcon="p10k configure"
alias t="tmux"
alias tn="tmux new-session -s"
alias ta="tmux attach"
alias ts="tmux source ~/.tmux.conf"
alias v="nvim"
alias vim="nvim"
alias cat="bat"
alias npd="pnpm run dev"
alias npw="pnpm run watch"
alias nps="pnpm run start"
alias npb="npm run build"
alias npiy="npm init -y"
alias pni='pnpm install'
alias pnid='pnpm add -D'
alias pnig='pnpm add -g'
alias npi="npm i"
alias npid="npm i -D"
alias npig="npm i --location=global"
alias npau="npm audit fix"
alias pnau="pnpm audit fix"
alias npaf="npm audit fix --force"
alias pnaf="pnpm audit fix --force"
alias snapi="snap install"
# alias disn="xrandr --output eDP-1 --off && killall conky"
# alias disf="xrandr --output eDP-1 --auto" # HDMI-1
alias dish="xrandr --output eDP-1 --off --output HDMI-1 --auto; nitrogen --restore"
alias dise="xrandr --output HDMI-1 --off --output eDP-1 --auto; nitrogen --restore"
alias disa='xrandr --output eDP-1 --primary --auto --right-of HDMI-1 --auto; nitrogen --restore'
alias sss='systemctl suspend'
alias afg="cd ~/.config/alacritty && nvim"
alias dfg="cd ~/.config/arco-dwm && nvim"
alias kfg="cd ~/.config/kitty && nvim"
alias lfg="cd ~/.config/lazygit && nvim"
alias mfg="cd ~/.moc/ && nvim"
alias rfg='cd ~/.config/ranger && nvim'
alias tfg="cd ~/.tmux && nvim"
alias sfg="cd ~/.config/arco-st && nvim"
alias nfg="cd ~/.config/nvim && nvim"
alias zfg="cd ~/.config/zsh && nvim"
alias blf='bluetooth off'
alias bln='bluetooth on'
alias bls="bluetoothctl scan on"  
alias blc="bluetoothctl connect CC:98:8B:A7:BB:38"  
alias blr="bluetoothctl connect"  
alias bli="bluetoothctl info"  
alias bld="bluetoothctl disconnect CC:98:8B:A7:BB:38"  
alias blp="bluetoothctl pair CC:98:8B:A7:BB:38"
alias wa="nmcli dev wifi list"
alias wt="wifi toggle"
alias ww="nmcli dev wifi connect ."
alias wr="nmcli dev wifi connect"
alias wd="nmcli dev disconnect"
alias ws="nmcli dev status"
alias wo="nmcli radio wifi on"
alias wi="nmcli --show-secrets connection show"
alias mntl="sudo lsblk -l" # fdisk
alias pacu="sudo pacman -Syyu"
alias pacl="sudo rm /var/lib/pacman/db.lck"
alias yaya="yay -Sua --noconfirm"
alias yayu="yay -Syyu"
alias yays="yay -Syu --noconfirm"
alias paci="sudo pacman -S"
alias pacu="sudo pacman -Syyu"
alias pacs="sudo pacman -Syu --noconfirm"
alias alis="alias | grep"
alias luamake="/home/pheon/.config/nvim/lua-language-server/3rd/luamake/luamake"
alias icat="kitty +kitten icat --align=left"
alias lis="live-server"
alias winfo='xprop'
alias c='clear'
alias rn='ranger'
alias ari='aria2c --file-allocation=none -c -x 10 -d . -Z'
alias tp='toipe'
alias pnu='sudo pnpm add -g pnpm'
alias npu='sudo npm update --location=global'
alias lg='lazygit'
alias pnb='pnpm run build'
alias pnt='pnpm create tauri-app'
alias deni='deno run -A -r https://fresh.deno.dev'
alias dens='deno task start'
alias y="yarn"
alias ya="yarn add"
alias yr="yarn remove"
alias yb="yarn build"
alias yt="yarn turbo run build"
alias yg="yarn global add"
alias yv="yarn add --dev"
alias yd="yarn dev"
alias ys="yarn start"
alias yi="yarn init"
alias yx="yarn create next-app --typescript" # alt [ynx app-name]
alias ye="yarn add --ignore-engines"
alias f="fuck"
alias fsg="flameshot gui -p ~/Downloads/Picture"
alias vector="~/.vector/bin/vector"
alias bl="bluetooth on && bluetoothctl connect CC:98:8B:A7:BB:38"
alias psc="pscale"
alias pft="prisma format"
alias psh="prisma db push"
alias pll="prisma pull"
alias pnt="prisma init"
alias pgn="prisma generate"
alias pst="prisma studio"
alias pscon="pscale connect '$1' '$2' --port 3306"  # 1: db, 2: branch, 3: port
alias pscll="pscale shell '$1' '$2'"  # 1: db, 2: branch
alias wfn="nmcli connection add type ethernet con-name ether ifname"
alias wfu="nmcli con up"
alias mcon="cd ~/.config/dmenu && mv config.h bu-config.h && sudo make install"
alias dcon="cd ~/.config/arco-dwm && mv config.h bu-config.h && sudo make install"
alias scon="cd ~/.config/arco-st && mv config.h bu-config.h && sudo make install"
alias nv="~/Documents/Neovim/nvim-linux64/bin/nvim"
alias tcol="cp ~/.config/nvim/tokyo/colors.lua ~/.local/share/nvim/site/pack/packer/start/tokyonight.nvim/lua/tokyonight/colors.lua"
alias rb="reboot"
alias fsh="shfmt -l -w ."
